USE fosterPets_db;
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Cheeseburger", "m", "Young", true, true, "https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/reference_guide/cats_and_excessive_meowing_ref_guide/1800x1200_cats_and_excessive_meowing_ref_guide.jpg");
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Charles", "m", "Old", true, false, "https://img.huffingtonpost.com/asset/5dcc613f1f00009304dee539.jpeg?cache=QaTFuOj2IM&ops=crop_834_777_4651_2994%2Cscalefit_720_noupscale");
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Bobo", "f", "Adult", false, true,"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cat-named-dymka-in-the-veterinary-clinic-best-where-it-had-news-photo-1582304174.jpg");
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Yeezy", "m", "Young", true, true, "https://images.squarespace-cdn.com/content/v1/55c945e0e4b04386fb9f8162/1531837146897-RJA7PBBKEMGJWGAGDA2B/ke17ZwdGBToddI8pDm48kLkXF2pIyv_F2eUT9F60jBl7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0iyqMbMesKd95J-X4EagrgU9L3Sa3U8cogeb0tjXbfawd0urKshkc5MgdBeJmALQKw/cute-3252251.jpg?format=2500w");
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Tater", "f", "Young", true, true, "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2019/09/931/524/cat-getty-images.jpg?ve=1&tl=1");
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Mellow", "m", "Adult", false, false, "https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/WALN4MAIT4I6VLRIPUMJQAJIME.jpg");
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Gertie", "f", "Old", false, true, "https://media.wired.com/photos/5e1e646743940d0008009167/master/pass/Science_Cats-84873657.jpg");
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Ketchup", "f", "Young", true, true, "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRaUTh_vg5Pmj2ddnp1PAdQUBHcHiX2jGgrhm_ba8cAjxw30Pbg&usqp=CAU");
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Marshall", "m", "Adult", true, true, "https://images.theconversation.com/files/280024/original/file-20190618-118505-aag3r7.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=496&fit=clip");
INSERT INTO cats (cat_name, cat_gender, cat_age, kid_friendly, animal_friendly, cat_photo) VALUES ("Portland", "m", "Old", true, true, "https://vcahospitals.com/-/media/vca/images/lifelearn-images/fat_cat.png?la=en&hash=3FE74EC481B6EBFACC946494A2576F33");


INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Horton", "m", "Young", true, true, "https://cdn.mos.cms.futurecdn.net/JzqhuEDTRfCZKMKHUxPySB.jpg");
INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Mooney", "m", "Old", true, false, "https://www.cesarsway.com/wp-content/uploads/2015/06/AdobeStock_222480718.jpeg");
INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Bubba", "f", "Adult", false, true, "https://media4.s-nbcnews.com/i/newscms/2019_23/2885811/190606-border-collie-mc-1318_5b1706791f4ae9ddb3029540a98f7e08.JPG");
INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Banjo", "m", "Young", true, true,"https://www.sdhumane.org/assets/images/standard/stock-900/stock1118-890-16.jpg");
INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Peep", "f", "Young", true, true, "https://images2.minutemediacdn.com/image/upload/c_crop,h_2788,w_4960,x_0,y_255/f_auto,q_auto,w_1100/v1554918537/shape/mentalfloss/istock-488657289.jpg");
INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Loki", "m", "Adult", false, false, "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gettyimages-1094874726.png?crop=0.542xw:0.814xh;0.0472xw,0.127xh&resize=640:*");
INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Bellow", "f", "Old", false, true, "https://assets3.thrillist.com/v1/image/2843959/size/tmg-article_tall;jpeg_quality=20.jpg");
INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Ronald", "f", "Young", true, true, "https://www.aspcapro.org/sites/default/files/styles/image_component/public/resource/card/image/dog-body-language-scared.jpg?itok=LRdhcHFU");
INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Harold", "m", "Adult", true, true, "https://www.thesprucepets.com/thmb/UC31tGFZDNaVS6tWXdUxwgkCmqI=/1885x1414/smart/filters:no_upscale()/dog-laying-on-carpet-and-holding-stuffed-dog-toy-547494903-5c3d9a2946e0fb000178473d.jpg");
INSERT INTO dogs (dog_name, dog_gender, dog_age, kid_friendly, animal_friendly, dog_photo) VALUES ("Potato", "m", "Old", true, true, "https://t7-live-ahsd8.nyc3.cdn.digitaloceanspaces.com/animalhumanesociety.org/files/media/image/2017-07/tom.jpg");